/dart_config:
  ros__parameters:
    auto_fw_calibration: false
    auto_yaw_calibration: false
    dart_selection:
      - 7.25
      - 7.26
      - 7.27
      - 7.32
    target_delta_height: 5.000000
    target_distance: 0.000000
    target_fw_velocity: 5273
    target_fw_velocity_launch_offset:
      - 250
      - 90
      - 120
      - -50
    target_fw_velocity_offset: 0
    target_fw_velocity_ratio: 1.200000
    target_yaw_angle: 148966
    target_yaw_angle_offset: 0
    target_yaw_launch_angle_offset:
      - 2500
      - -9600
      - 2000
      - 1500
    target_yaw_x_axis: 1024.000000