/dart_config:
  ros__parameters:
    auto_fw_calibration: false
    auto_yaw_calibration: false
    dart_selection:
      - "NULL"
      - "NULL"
      - "NULL"
      - "NULL"
    target_fw_velocity: 5670
    target_fw_velocity_launch_offset:
      - 0
      - 0
      - 0
      - 0
    target_fw_velocity_offset: 0
    target_fw_velocity_ratio: 0.000000
    target_yaw_angle: 248522
    target_yaw_angle_offset: 0
    target_yaw_launch_angle_offset:
      - 0
      - 0
      - 0
      - 0