/dart_config:
  ros__parameters:
    auto_fw_calibration: false
    auto_yaw_calibration: false
    dart_selection:
      - "NULL"
      - "NULL"
      - "NULL"
      - "NULL"
    target_fw_velocity: 4950
    target_fw_velocity_launch_offset:
      - 0
      - 0
      - 0
      - 0
    target_fw_velocity_offset: 0
    target_fw_velocity_ratio: 1.414000
    target_yaw_angle: 213083
    target_yaw_angle_offset: -95
    target_yaw_launch_angle_offset:
      - 0
      - 0
      - 0
      - 0