/dart_config:
  ros__parameters:
    auto_fw_calibration: false
    auto_yaw_calibration: true
    dart_selection:
      - 7.34
      - 7.33
      - 7.27
      - 7.32
    target_delta_height: 0.240000
    target_distance: 25.500000
    target_fw_velocity: 6851
    target_fw_velocity_launch_offset:
      - 100
      - -1506
      - -343
      - -107
    target_fw_velocity_offset: 0
    target_fw_velocity_ratio: 0.900000
    target_yaw_angle: 128693
    target_yaw_angle_offset: 0
    target_yaw_launch_angle_offset:
      - -7000
      - 0
      - -2200
      - -7100
    target_yaw_x_axis: 892.000000